class MeetingDetail{
  int meetingId;
  int id;
  String city;
  String summary;
  DateTime date;
  bool read;
  int approve;
  String type;
  String loveType;
  int age;
  int marry;
  int height;
  String job;
  String figure;
  String xingzuo;
  String content;
  String registId;
  String enlistersName;
  int score;
  int pics;
  String reason;
}